### ISSUE TITLE
[BUG] - `query ledger-state` outputs CBOR after nodes upgrade

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#3859]
*Internal*   if an IOHK staff member.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
After upgrading nodes of local cluster from release 1.34.1 to current master, the `cardano-cli query ledger-state --testnet-magic 42 --cardano-mode` command no longer outputs JSON, but CBOR.

**Steps to reproduce**
Steps used to reproduce the behavior:
1. run local cluster nodes with release 1.24.1
2. run QA smoke tests
3. restart cluster nodes with binaries built from current master
4. run smoke tests again
5. see the error

The resulting output:
[upgraded_ledger_state.json.gz](https://github.com/input-output-hk/cardano-node/files/8679646/upgraded_ledger_state.json.gz)

**System info (please complete the following information):**
- OS Name: Fedora 35
- Node version: `0e242043aa4d94b1e0a7ac28dc3b3bc1fb2d25d7`

**Comment by mkoura** [comment]
The `query protocol-state` now returns CBOR as well. Same situation as in the original issue (upgraded node).

**Comment by dorin100** [comment]
@mkoura - is `query stake-snapshot` in the same situation as the above 2 commands?

**Comment by mkoura** [comment]
@dorin100 per our new automated tests for this issue, following commands are affected:
* `query ledger-state`
* `query protocol-state`
* `query stake-snapshot`
* `query pool-params`

**Comment by Jimbo4350** [comment]
@mkoura can you confirm the following commands still output CBOR:
- query ledger-state -> Outputs JSON for me
- query protocol-state -> Outputs JSON for me
- query stake-snapshot -> Outputs JSON for me
- query pool-params -> Outputs JSON for me

**Comment by saratomaz** [comment]
Fixed, the commands are already returning json.

Verified with the following tests:
test_ledger_state
test_stake_snapshot
test_pool_params
test_protocol_state_keys

**Comment by mkoura** [comment]
Not fixed, the important part is "After upgrading nodes of local cluster from release 1.34.1 to current master". We still get CBOR instead of JSON in this scenario.

**Comment by Jimbo4350** [comment]
@mkoura  I just tested current `master`. Please paste your commands and outputs.

**Comment by mkoura** [comment]
Not sure if this can be tested in isolation. Our job does following:
* start local network with node version running on mainnet (1.34.1 atm)
* run smoke tests (370+), so there is some history
* upgrade cardano-node to latest master and restart node processes with updated binaries
* re-run all smoke tests

After the node is upgraded to master (f5161e5bee1c733c56557e202e22e636c845634f in last failed job), we run simple query with output to stdout (without `--out-file`) in the failing tests. At the moment I've got only output of `cardano-cli query protocol-state` available in testing artifacts - [test_protocol_state_keys_ci0_nge_protocol_state.out.gz](https://github.com/input-output-hk/cardano-node/files/9154990/test_protocol_state_keys_ci0_nge_protocol_state.out.gz)

I'll play with it more after my PTO if needed.

**Comment by Jimbo4350** [comment]
Current `master` is `621311f495dd4ed471482527104e256ac6971464`

> I'll play with it more after my PTO if needed.

Please don't respond if you are on PTO :)

**Comment by mkoura** [comment]
Sorry, wrong rev, we tested it with commit 2be07bbb74d5ff910aba35f87f47cd8c07151fc7 during last nightly run.

**Comment by Jimbo4350** [comment]
@mkoura  Can you test it with the latest `master`? It's working for @saratomaz and myself.

**Comment by mkoura** [comment]
Still the same issue on 803881bd1d662f2556f653c2f0483735f5a0a2c0

It is not working for @saratomaz, she didn't test is on upgraded nodes, which is a required condition.
All the affected commands work if the nodes were NOT upgraded.

**Comment by newhoggy** [comment]
Please verify that the version of `cardano-cli` matches exactly with the version of `cardano-node` that the `cardano-cli` is connecting to.

**Comment by CarlosLopezDeLara** [comment]
Closing as non-issue. We have confirmation that there was a problem related to the use of different node and cli versions.
